### ISSUE TITLE
react-navigationのmoduleが読み込まれない

### ISSUE THREAD

**Issue by hudsoncliff** [mickamy/WeatherForecast#2]
初めまして。
WEB+DEBvol.102をで掲載されていた、ReactNativeの実戦投入のチュートリアルを試しているのですが、表題の部分でつまづいたので、質問をさせてください。

画面遷移の機能を導入するために、react-navigationを導入したところ、シミュレーターで次のエラーが出ました。
Unable to resolve module 'react-navigation/src/TypeDefinition' from PATH Module does not exist in the module map

TypeDefinitionというファイルを参照できていないのかと思い、まずはファイルの存在を確かめて見たのですが、サンプルにあるような形で、node_modules/react-navigation/src/内を確認して見たところ、TypeDefinitionというファイルが存在していませんでした。

react-navigationのバージョンが最新でチュートリアルとは違うものを使っているので、これが原因かなと考え、package.json内でreact-navigationのバージョンをチュートリアルと同じに変更してからさいどnpm installをかけて見てビルドを試みたのですが、状況は変わらずでした。

react-navigationを導入した段階でTypeDefinintionも自動的に生成されるのが通常の挙動なのでしょうか？

**Comment by mickamy** [comment]
@hudsoncliff 反応遅くて申し訳ありません 🙇 
問題は解決されましたでしょうか？
依然発生するようでしたら調べてみますがいかがでしょう？

**Comment by hudsoncliff** [comment]
返信ありがとうございます。
その後、自分のファイルの方チェックしまして、package-lock.json内に記載されている"react-navigation"のバージョンがサンプルのものとは違っていたことに気がつき、そちらを修正したら無事に解決しました。
